{% set version = "0.0.1" %}

package:
  name: technician-routing
  version: {{ version }}

build:
  number: 6
  noarch: python

requirements:
  run:
    - python
    - numpy >=1.11
    # - geopy >=2.4.1
